### PR TITLE
Refactor files

### PR DESCRIPTION
**Pull request by Aschen**
## What does this PR do?

Refactor the files structures. Keep controllers, core classes, and protocols together.

File containing class begin with an uppercase.

Also internally rename some classes (0 API change)

```
src
├── controllers
│   ├── Auth.js
│   ├── Base.js
│   ├── Bulk.js
│   ├── Collection.js
│   ├── Document.js
│   ├── Index.js
│   ├── MemoryStorage.js
│   ├── Realtime.js
│   ├── Security.js
│   └── Server.js
├── core
│   ├── Jwt.js
│   ├── KuzzleEventEmitter.js
│   ├── Room.js
│   ├── searchResult
│   │   ├── Document.js
│   │   ├── index.js
│   │   ├── Profile.js
│   │   ├── Role.js
│   │   ├── SearchResultBase.js
│   │   ├── Specifications.js
│   │   └── User.js
│   └── security
│       ├── Profile.js
│       ├── Role.js
│       └── User.js
├── KuzzleError.js
├── Kuzzle.js
├── protocols
│   ├── abstract
│   │   ├── Base.js
│   │   ├── PendingRequest.js
│   │   └── Realtime.js
│   ├── Http.js
│   ├── index.js
│   ├── routes.json
│   └── WebSocket.js
└── utils
    ├── proxify.js
    └── uuidv4.js
```

### How to review this PR

Just clone the branch and open it in your code editor

### CODE REVIEW

**Comment by Aschen** [comment]
> Is this really meant to be merged on `master`?

I wanted to merge it on master and then marge back on `7-dev`. 
Do you see any reason not to?

**Comment by scottinet** [comment]
That's the other way around: can you tell me what would be the benefit of merging this PR directly on master?

**Comment by scottinet** [comment]
I gave it some thoughts, and I think it depends if there are pending modifications in the develop branch. If so, then this PR should be merged on the develop branch, otherwise it can be painful to resolve conflicts.
If not, then as long as if it's merged quickly, then I guess it doesn't make a difference whether it's merged on master first or not.

**Comment by Aschen** [comment]
@scottinet I changed the target branch for `7-dev` since there is already a pending PR

**Pull request merged**
