### PR TITLE
Allow creating a user without specifying the id

### PR DESCRIPTION
**Pull request by xbill82**
# Description
Aligning the API to the core. The ID is no longer mandatory to create a user, since Kuzzle auto-generates one.

### CODE REVIEW

**Comment by samniisan** [comment]
You should do the same for ``createRestrictedUser``

**Comment by dbengsch** [comment]
@xbill82 did you check other SDKs as well ?

**Comment by xbill82** [comment]
@dbengsch yep, the Android needs the same fix

**Comment by xbill82** [comment]
Ok @samniisan things should be fixed now!

**Comment by scottinet** [comment]
Waiting for this PR to be created on the Android SDK project to merge this one.

**Pull request merged**
