### PR TITLE
Support secure connection

### PR DESCRIPTION
**Pull request by Filsh**

### CODE REVIEW

**Comment by Filsh** [comment]
https://github.com/kuzzleio/sdk-javascript/pull/103/commits/9c9031d11d3a4561d64356a4d47a7317b3e22cfb because test failed https://travis-ci.org/kuzzleio/sdk-javascript/builds/155789950

**Comment by stafyniaksacha** [comment]
+1

**Comment by scottinet** [comment]
+1

**Comment by scottinet** [comment]
-1 for the merge: as we're using [gitflow](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/), can you please re-create this PR with kuzzleio:develop as the target branch?

**Pull request merged**
