### PR TITLE
fixed setContent and update in KuzzleSecurityDocument

### PR DESCRIPTION
**Pull request by scottinet**
* The `KuzzleSecurityDocument.setContent` method was taking a `replace` argument, which is wrong: because of the way security document objects are constructed, this argument had no effect
* The `KuzzleSecurityDocument.update` method was updating the internal object content with the `content` argument instead of the updated source of the document

### CODE REVIEW

**Comment by AnthonySendra** [comment]
+1

**Comment by dbengsch** [comment]
+1

**Comment by xbill82** [comment]
Seems Legit! +1

**Comment by scottinet** [comment]
@xbill82 > well in fact, the SDK documentation didn't change in that regard. I implemented the `setContent` method in security objects by copying/pasting the one in `KuzzleDocument` without giving it a second thought, and that was clearly wrong.

So you may view this PR as a way to fix the SDK regarding the documentation. :-)

**Pull request merged**
