### PR TITLE
Memory storage implementation 

### PR DESCRIPTION
**Pull request by benoitvidis**
Sidenote: May be worth checking if it is worth factorizing Kuzzle's stub among all tests.

### CODE REVIEW

**Comment by scottinet** [comment]
+1!

**Comment by jenow** [comment]
+1

**Comment by benoitvidis** [comment]
For the time being, there are some remaining debug outputs.. I am fixing it and the pr test failure.
Sorry for that...

**Comment by stafyniaksacha** [comment]
+1

**Pull request merged**
