### PR TITLE
Re-order dependencies to correct emplacement.

### PR DESCRIPTION
**Pull request by ScreamZ**
## What does this PR do?

This is fixing dependencies that should be in `dev dependencies` as they are not related to runtime but build phase.

Regards

### CODE REVIEW

**Comment by Aschen** [comment]
After talking with @scottinet, it appear that we have to keep these dependencies in order to build the SDK dist

**Comment by Aschen** [comment]
I put the PR in wip so we don't forget to remove the dependencies later

**Comment by scottinet** [comment]
@Aschen > we should write a new (internal) issue instead: once we release the SDK, we need a little more than just moving the dependencies back to the devDependencies section; we need also to properly configure the npm publish action, to force it to build the `dist` folder

**Comment by scottinet** [comment]
@Aschen > we should write a new (internal) issue instead: once we release the SDK, we need a little more than just moving the dependencies back to the devDependencies section; we need also to properly configure the npm publish action, to force it to build the `dist` folder.

**Comment by Aschen** [comment]
@scottinet Done: https://jira.kaliop.net/browse/KZL-983
I close this PR.

**Pull request closed without merging**
